import gnupg

gpg = gnupg.GPG(gnupghome=".gnupg")

fd = open('Alice/plaintext', 'rb')
status = gpg.encrypt_file(fd, recipients=['alice'], output='plaintext.encrypted')

print(status.ok)
print(status.stderr)

print('---------------------')
fp = gpg.list_keys(True)
print(fp)
for key in fp:
    if (key['uids'][0] == 'Autogenerated Key <' + 'bob' + '>'):
        print('1')
    print(key['uids'])